name: Continuous Integration
on: push
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Sync dev dependencies
        run: uv sync --extra dev

      - name: Run ruff
        run: uv run ruff check .

      - name: Run pytest
        run: uv run pytest

      - name: Build
        run: uv build
